name: "Health Check"

on:
    workflow_dispatch

jobs:
    health_check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run Flask Server in Backgorund
              run: |
                python app.py
                sleep 5
            
            - name: Test API Endpoint
              run: curl -X GET http://127.0.0.1:3000/
                